title: Aditya Puttaparthi Tirumala
description: Principal Data Scientist, Data Science Leader
url: "https://adityaputtaparthitirumala.com"

nav:
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: DeepCausalMMM
    url: /deepcausalmmm/
  - title: Talks & Service
    url: /talks-service/
  - title: About
    url: /about/

plugins:
  - jekyll-seo-tag
