title: Aditya Puttaparthi Tirumala
description: Principal Data Scientist — Product & Marketing Data Science
url: "https://adityaputtaparthitirumala.com"

nav:
  - title: Research
    url: /research/
  - title: Open Source
    url: /open-source/
  - title: Publications & Talks
    url: /publications-talks/
  - title: Service
    url: /service/
  - title: Contact
    url: /contact/

plugins:
  - jekyll-seo-tag
